spring:
  application:
    name: demo2

custom:
  cookie: _grayver_=always; _u2token_=c55841b59d8b4206a4bd41869924a953; _u2eid_=4; _u2comtype_=0; _u2uid_=1000433633; _nwcf_=gM6HTFS8JXUNVumkN70PdWRx4uXHBpEmIjphSICnkQHGUftUCQzXtJrWqmo3Lki0v14J3jTY+z5FQRCWrDKew9T3cDUzUy4wAmW1q53coLOKOGdyFsut4XY2rqm1NY1qybPJ8IrMTqtq9S+3iB8sws6Xzt+4/rXvq1Ht4bqCE+SwDS4RgmzOsIeeEo71hVsxavD7B6bDUE8=; _grayver_=never; _tzone_=UTC+08:00; _nwcfl_=li4/svxTXKsIhsADXDZ+KApGdLUl/T/L; _etime_=1666851329676; _u2cid_=60000260; _lcode_=zh_CN; loginType=WEB; _grayver_=never;

feign:
  client:
    config:
      # 全局配置
      default:
        logger-level: BASIC # 日志级别
  # Feign Apache HttpClient 配置项，对应 FeignHttpClientProperties 配置属性类
  httpclient:
    enabled: true # 是否开启。默认为 true
    max-connections: 200 # 最大连接数。默认为 200
    max-connections-per-route: 50 # 每个路由的最大连接数。默认为 50。router = host + port

logging:
  level:
    com.example.demo2.feign: debug