spring:
  application:
    name: demo-consumer # Spring 应用名

feign:
  # Feign 客户端配置，对应 FeignClientProperties 配置属性类
  client:
    # config 配置项是 Map 类型。key 为 Feign 客户端的名字，value 为 FeignClientConfiguration 对象
    config:
      # 全局级别配置
      default:
        logger-level: BASIC
  # Feign Apache HttpClient 配置项，对应 FeignHttpClientProperties 配置属性类
  httpclient:
    enabled: true # 是否开启。默认为 true
    max-connections: 200 # 最大连接数。默认为 200
    max-connections-per-route: 50 # 每个路由的最大连接数。默认为 50。router = host + port



custom:
  cookie: _u2token_=5360d75caf174dc285e261261efbba2b; _u2comtype_=0; _u2cid_=60000004; loginType=WEB; _tzone_=UTC+08:00; _lcode_=zh_CN; _etime_=1662559689411; _u2uid_=1000818622; _nwcf_=mehTVWVqs/eTNrKDC4KTpLTQVF/0apK/9TdC5ZFgLKgOnCtVbygD8TOjRdqD2aNvAiYP8qOIXrE2IdIBSbA4cACPPDC3WRneUl6OyQ+lr2zppw6qRJH12H4GWsAV7UFEd3FmHauM+jBqy7EJVMeRKwWsGTcK6TZHwvC3rcu8W/HYgqTUpi3i2H9+rZp4lMQjf4/wu+7dJfznw45CUqfaEQ==; _nwcfl_=slVV74A5aYV/btA94U9w0gpGdLUl/T/L; _u2eid_=414573; _grayver_=never; _grayver_=never;